name: CI Backend Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "devellopment", "developpmentTeam1" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Optimising speed by caching the .jar

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: Run All Tests
        run: mvn -B test

      - name: Technical Debt Check (Optional)
        # Code quality need to be checked
        run: echo "Analyse SonarCloud or Checkstyle can be added here"
